//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WebApp.DB.marykay
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class MaryKayDBEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“MaryKayDBEntities”部分中的连接字符串初始化新 MaryKayDBEntities 对象。
        /// </summary>
        public MaryKayDBEntities() : base("name=MaryKayDBEntities", "MaryKayDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MaryKayDBEntities 对象。
        /// </summary>
        public MaryKayDBEntities(string connectionString) : base(connectionString, "MaryKayDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 MaryKayDBEntities 对象。
        /// </summary>
        public MaryKayDBEntities(EntityConnection connection) : base(connection, "MaryKayDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_answer> tbl_answer
        {
            get
            {
                if ((_tbl_answer == null))
                {
                    _tbl_answer = base.CreateObjectSet<tbl_answer>("tbl_answer");
                }
                return _tbl_answer;
            }
        }
        private ObjectSet<tbl_answer> _tbl_answer;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_employeeMK> tbl_employeeMK
        {
            get
            {
                if ((_tbl_employeeMK == null))
                {
                    _tbl_employeeMK = base.CreateObjectSet<tbl_employeeMK>("tbl_employeeMK");
                }
                return _tbl_employeeMK;
            }
        }
        private ObjectSet<tbl_employeeMK> _tbl_employeeMK;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_questions> tbl_questions
        {
            get
            {
                if ((_tbl_questions == null))
                {
                    _tbl_questions = base.CreateObjectSet<tbl_questions>("tbl_questions");
                }
                return _tbl_questions;
            }
        }
        private ObjectSet<tbl_questions> _tbl_questions;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_record> tbl_record
        {
            get
            {
                if ((_tbl_record == null))
                {
                    _tbl_record = base.CreateObjectSet<tbl_record>("tbl_record");
                }
                return _tbl_record;
            }
        }
        private ObjectSet<tbl_record> _tbl_record;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_view> tbl_view
        {
            get
            {
                if ((_tbl_view == null))
                {
                    _tbl_view = base.CreateObjectSet<tbl_view>("tbl_view");
                }
                return _tbl_view;
            }
        }
        private ObjectSet<tbl_view> _tbl_view;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<marykay_Set> marykay_Set
        {
            get
            {
                if ((_marykay_Set == null))
                {
                    _marykay_Set = base.CreateObjectSet<marykay_Set>("marykay_Set");
                }
                return _marykay_Set;
            }
        }
        private ObjectSet<marykay_Set> _marykay_Set;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<korea_answer> korea_answer
        {
            get
            {
                if ((_korea_answer == null))
                {
                    _korea_answer = base.CreateObjectSet<korea_answer>("korea_answer");
                }
                return _korea_answer;
            }
        }
        private ObjectSet<korea_answer> _korea_answer;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<korea_employeeMK> korea_employeeMK
        {
            get
            {
                if ((_korea_employeeMK == null))
                {
                    _korea_employeeMK = base.CreateObjectSet<korea_employeeMK>("korea_employeeMK");
                }
                return _korea_employeeMK;
            }
        }
        private ObjectSet<korea_employeeMK> _korea_employeeMK;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<korea_questions> korea_questions
        {
            get
            {
                if ((_korea_questions == null))
                {
                    _korea_questions = base.CreateObjectSet<korea_questions>("korea_questions");
                }
                return _korea_questions;
            }
        }
        private ObjectSet<korea_questions> _korea_questions;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<korea_record> korea_record
        {
            get
            {
                if ((_korea_record == null))
                {
                    _korea_record = base.CreateObjectSet<korea_record>("korea_record");
                }
                return _korea_record;
            }
        }
        private ObjectSet<korea_record> _korea_record;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 tbl_answer EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_answer(tbl_answer tbl_answer)
        {
            base.AddObject("tbl_answer", tbl_answer);
        }
    
        /// <summary>
        /// 用于向 tbl_employeeMK EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_employeeMK(tbl_employeeMK tbl_employeeMK)
        {
            base.AddObject("tbl_employeeMK", tbl_employeeMK);
        }
    
        /// <summary>
        /// 用于向 tbl_questions EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_questions(tbl_questions tbl_questions)
        {
            base.AddObject("tbl_questions", tbl_questions);
        }
    
        /// <summary>
        /// 用于向 tbl_record EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_record(tbl_record tbl_record)
        {
            base.AddObject("tbl_record", tbl_record);
        }
    
        /// <summary>
        /// 用于向 tbl_view EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_view(tbl_view tbl_view)
        {
            base.AddObject("tbl_view", tbl_view);
        }
    
        /// <summary>
        /// 用于向 marykay_Set EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTomarykay_Set(marykay_Set marykay_Set)
        {
            base.AddObject("marykay_Set", marykay_Set);
        }
    
        /// <summary>
        /// 用于向 korea_answer EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTokorea_answer(korea_answer korea_answer)
        {
            base.AddObject("korea_answer", korea_answer);
        }
    
        /// <summary>
        /// 用于向 korea_employeeMK EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTokorea_employeeMK(korea_employeeMK korea_employeeMK)
        {
            base.AddObject("korea_employeeMK", korea_employeeMK);
        }
    
        /// <summary>
        /// 用于向 korea_questions EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTokorea_questions(korea_questions korea_questions)
        {
            base.AddObject("korea_questions", korea_questions);
        }
    
        /// <summary>
        /// 用于向 korea_record EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTokorea_record(korea_record korea_record)
        {
            base.AddObject("korea_record", korea_record);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MaryKayDBModel", Name="korea_answer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class korea_answer : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 korea_answer 对象。
        /// </summary>
        /// <param name="aId">aId 属性的初始值。</param>
        public static korea_answer Createkorea_answer(global::System.Int32 aId)
        {
            korea_answer korea_answer = new korea_answer();
            korea_answer.aId = aId;
            return korea_answer;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 aId
        {
            get
            {
                return _aId;
            }
            set
            {
                if (_aId != value)
                {
                    OnaIdChanging(value);
                    ReportPropertyChanging("aId");
                    _aId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("aId");
                    OnaIdChanged();
                }
            }
        }
        private global::System.Int32 _aId;
        partial void OnaIdChanging(global::System.Int32 value);
        partial void OnaIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> qId
        {
            get
            {
                return _qId;
            }
            set
            {
                OnqIdChanging(value);
                ReportPropertyChanging("qId");
                _qId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qId");
                OnqIdChanged();
            }
        }
        private Nullable<global::System.Int32> _qId;
        partial void OnqIdChanging(Nullable<global::System.Int32> value);
        partial void OnqIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> rId
        {
            get
            {
                return _rId;
            }
            set
            {
                OnrIdChanging(value);
                ReportPropertyChanging("rId");
                _rId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rId");
                OnrIdChanged();
            }
        }
        private Nullable<global::System.Int32> _rId;
        partial void OnrIdChanging(Nullable<global::System.Int32> value);
        partial void OnrIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aContent
        {
            get
            {
                return _aContent;
            }
            set
            {
                OnaContentChanging(value);
                ReportPropertyChanging("aContent");
                _aContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("aContent");
                OnaContentChanged();
            }
        }
        private global::System.String _aContent;
        partial void OnaContentChanging(global::System.String value);
        partial void OnaContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aRemark
        {
            get
            {
                return _aRemark;
            }
            set
            {
                OnaRemarkChanging(value);
                ReportPropertyChanging("aRemark");
                _aRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("aRemark");
                OnaRemarkChanged();
            }
        }
        private global::System.String _aRemark;
        partial void OnaRemarkChanging(global::System.String value);
        partial void OnaRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MaryKayDBModel", Name="korea_employeeMK")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class korea_employeeMK : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 korea_employeeMK 对象。
        /// </summary>
        /// <param name="eId">eId 属性的初始值。</param>
        public static korea_employeeMK Createkorea_employeeMK(global::System.Int32 eId)
        {
            korea_employeeMK korea_employeeMK = new korea_employeeMK();
            korea_employeeMK.eId = eId;
            return korea_employeeMK;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 eId
        {
            get
            {
                return _eId;
            }
            set
            {
                if (_eId != value)
                {
                    OneIdChanging(value);
                    ReportPropertyChanging("eId");
                    _eId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("eId");
                    OneIdChanged();
                }
            }
        }
        private global::System.Int32 _eId;
        partial void OneIdChanging(global::System.Int32 value);
        partial void OneIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eNumber
        {
            get
            {
                return _eNumber;
            }
            set
            {
                OneNumberChanging(value);
                ReportPropertyChanging("eNumber");
                _eNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eNumber");
                OneNumberChanged();
            }
        }
        private global::System.String _eNumber;
        partial void OneNumberChanging(global::System.String value);
        partial void OneNumberChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eName
        {
            get
            {
                return _eName;
            }
            set
            {
                OneNameChanging(value);
                ReportPropertyChanging("eName");
                _eName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eName");
                OneNameChanged();
            }
        }
        private global::System.String _eName;
        partial void OneNameChanging(global::System.String value);
        partial void OneNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ePhone
        {
            get
            {
                return _ePhone;
            }
            set
            {
                OnePhoneChanging(value);
                ReportPropertyChanging("ePhone");
                _ePhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ePhone");
                OnePhoneChanged();
            }
        }
        private global::System.String _ePhone;
        partial void OnePhoneChanging(global::System.String value);
        partial void OnePhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eRemark
        {
            get
            {
                return _eRemark;
            }
            set
            {
                OneRemarkChanging(value);
                ReportPropertyChanging("eRemark");
                _eRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eRemark");
                OneRemarkChanged();
            }
        }
        private global::System.String _eRemark;
        partial void OneRemarkChanging(global::System.String value);
        partial void OneRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MaryKayDBModel", Name="korea_questions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class korea_questions : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 korea_questions 对象。
        /// </summary>
        /// <param name="qId">qId 属性的初始值。</param>
        public static korea_questions Createkorea_questions(global::System.Int32 qId)
        {
            korea_questions korea_questions = new korea_questions();
            korea_questions.qId = qId;
            return korea_questions;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 qId
        {
            get
            {
                return _qId;
            }
            set
            {
                if (_qId != value)
                {
                    OnqIdChanging(value);
                    ReportPropertyChanging("qId");
                    _qId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("qId");
                    OnqIdChanged();
                }
            }
        }
        private global::System.Int32 _qId;
        partial void OnqIdChanging(global::System.Int32 value);
        partial void OnqIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String qTitle
        {
            get
            {
                return _qTitle;
            }
            set
            {
                OnqTitleChanging(value);
                ReportPropertyChanging("qTitle");
                _qTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("qTitle");
                OnqTitleChanged();
            }
        }
        private global::System.String _qTitle;
        partial void OnqTitleChanging(global::System.String value);
        partial void OnqTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> qType
        {
            get
            {
                return _qType;
            }
            set
            {
                OnqTypeChanging(value);
                ReportPropertyChanging("qType");
                _qType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qType");
                OnqTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _qType;
        partial void OnqTypeChanging(Nullable<global::System.Int32> value);
        partial void OnqTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String qRemark
        {
            get
            {
                return _qRemark;
            }
            set
            {
                OnqRemarkChanging(value);
                ReportPropertyChanging("qRemark");
                _qRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("qRemark");
                OnqRemarkChanged();
            }
        }
        private global::System.String _qRemark;
        partial void OnqRemarkChanging(global::System.String value);
        partial void OnqRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MaryKayDBModel", Name="korea_record")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class korea_record : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 korea_record 对象。
        /// </summary>
        /// <param name="rId">rId 属性的初始值。</param>
        public static korea_record Createkorea_record(global::System.Int32 rId)
        {
            korea_record korea_record = new korea_record();
            korea_record.rId = rId;
            return korea_record;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 rId
        {
            get
            {
                return _rId;
            }
            set
            {
                if (_rId != value)
                {
                    OnrIdChanging(value);
                    ReportPropertyChanging("rId");
                    _rId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("rId");
                    OnrIdChanged();
                }
            }
        }
        private global::System.Int32 _rId;
        partial void OnrIdChanging(global::System.Int32 value);
        partial void OnrIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eId
        {
            get
            {
                return _eId;
            }
            set
            {
                OneIdChanging(value);
                ReportPropertyChanging("eId");
                _eId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eId");
                OneIdChanged();
            }
        }
        private Nullable<global::System.Int32> _eId;
        partial void OneIdChanging(Nullable<global::System.Int32> value);
        partial void OneIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> rBegintime
        {
            get
            {
                return _rBegintime;
            }
            set
            {
                OnrBegintimeChanging(value);
                ReportPropertyChanging("rBegintime");
                _rBegintime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rBegintime");
                OnrBegintimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _rBegintime;
        partial void OnrBegintimeChanging(Nullable<global::System.DateTime> value);
        partial void OnrBegintimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> rEndtime
        {
            get
            {
                return _rEndtime;
            }
            set
            {
                OnrEndtimeChanging(value);
                ReportPropertyChanging("rEndtime");
                _rEndtime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rEndtime");
                OnrEndtimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _rEndtime;
        partial void OnrEndtimeChanging(Nullable<global::System.DateTime> value);
        partial void OnrEndtimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> rDuration
        {
            get
            {
                return _rDuration;
            }
            set
            {
                OnrDurationChanging(value);
                ReportPropertyChanging("rDuration");
                _rDuration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rDuration");
                OnrDurationChanged();
            }
        }
        private Nullable<global::System.Int32> _rDuration;
        partial void OnrDurationChanging(Nullable<global::System.Int32> value);
        partial void OnrDurationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rRemark
        {
            get
            {
                return _rRemark;
            }
            set
            {
                OnrRemarkChanging(value);
                ReportPropertyChanging("rRemark");
                _rRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rRemark");
                OnrRemarkChanged();
            }
        }
        private global::System.String _rRemark;
        partial void OnrRemarkChanging(global::System.String value);
        partial void OnrRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MaryKayDBModel", Name="marykay_Set")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class marykay_Set : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 marykay_Set 对象。
        /// </summary>
        /// <param name="sId">sId 属性的初始值。</param>
        public static marykay_Set Createmarykay_Set(global::System.Int32 sId)
        {
            marykay_Set marykay_Set = new marykay_Set();
            marykay_Set.sId = sId;
            return marykay_Set;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 sId
        {
            get
            {
                return _sId;
            }
            set
            {
                if (_sId != value)
                {
                    OnsIdChanging(value);
                    ReportPropertyChanging("sId");
                    _sId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("sId");
                    OnsIdChanged();
                }
            }
        }
        private global::System.Int32 _sId;
        partial void OnsIdChanging(global::System.Int32 value);
        partial void OnsIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sProName
        {
            get
            {
                return _sProName;
            }
            set
            {
                OnsProNameChanging(value);
                ReportPropertyChanging("sProName");
                _sProName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sProName");
                OnsProNameChanged();
            }
        }
        private global::System.String _sProName;
        partial void OnsProNameChanging(global::System.String value);
        partial void OnsProNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> sIsOpen
        {
            get
            {
                return _sIsOpen;
            }
            set
            {
                OnsIsOpenChanging(value);
                ReportPropertyChanging("sIsOpen");
                _sIsOpen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sIsOpen");
                OnsIsOpenChanged();
            }
        }
        private Nullable<global::System.Boolean> _sIsOpen;
        partial void OnsIsOpenChanging(Nullable<global::System.Boolean> value);
        partial void OnsIsOpenChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> sUpdateTime
        {
            get
            {
                return _sUpdateTime;
            }
            set
            {
                OnsUpdateTimeChanging(value);
                ReportPropertyChanging("sUpdateTime");
                _sUpdateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sUpdateTime");
                OnsUpdateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _sUpdateTime;
        partial void OnsUpdateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnsUpdateTimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MaryKayDBModel", Name="tbl_answer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_answer : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_answer 对象。
        /// </summary>
        /// <param name="aId">aId 属性的初始值。</param>
        public static tbl_answer Createtbl_answer(global::System.Int32 aId)
        {
            tbl_answer tbl_answer = new tbl_answer();
            tbl_answer.aId = aId;
            return tbl_answer;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 aId
        {
            get
            {
                return _aId;
            }
            set
            {
                if (_aId != value)
                {
                    OnaIdChanging(value);
                    ReportPropertyChanging("aId");
                    _aId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("aId");
                    OnaIdChanged();
                }
            }
        }
        private global::System.Int32 _aId;
        partial void OnaIdChanging(global::System.Int32 value);
        partial void OnaIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> qId
        {
            get
            {
                return _qId;
            }
            set
            {
                OnqIdChanging(value);
                ReportPropertyChanging("qId");
                _qId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qId");
                OnqIdChanged();
            }
        }
        private Nullable<global::System.Int32> _qId;
        partial void OnqIdChanging(Nullable<global::System.Int32> value);
        partial void OnqIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> rId
        {
            get
            {
                return _rId;
            }
            set
            {
                OnrIdChanging(value);
                ReportPropertyChanging("rId");
                _rId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rId");
                OnrIdChanged();
            }
        }
        private Nullable<global::System.Int32> _rId;
        partial void OnrIdChanging(Nullable<global::System.Int32> value);
        partial void OnrIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aContent
        {
            get
            {
                return _aContent;
            }
            set
            {
                OnaContentChanging(value);
                ReportPropertyChanging("aContent");
                _aContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("aContent");
                OnaContentChanged();
            }
        }
        private global::System.String _aContent;
        partial void OnaContentChanging(global::System.String value);
        partial void OnaContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aRemark
        {
            get
            {
                return _aRemark;
            }
            set
            {
                OnaRemarkChanging(value);
                ReportPropertyChanging("aRemark");
                _aRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("aRemark");
                OnaRemarkChanged();
            }
        }
        private global::System.String _aRemark;
        partial void OnaRemarkChanging(global::System.String value);
        partial void OnaRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MaryKayDBModel", Name="tbl_employeeMK")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_employeeMK : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_employeeMK 对象。
        /// </summary>
        /// <param name="eId">eId 属性的初始值。</param>
        public static tbl_employeeMK Createtbl_employeeMK(global::System.Int32 eId)
        {
            tbl_employeeMK tbl_employeeMK = new tbl_employeeMK();
            tbl_employeeMK.eId = eId;
            return tbl_employeeMK;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 eId
        {
            get
            {
                return _eId;
            }
            set
            {
                if (_eId != value)
                {
                    OneIdChanging(value);
                    ReportPropertyChanging("eId");
                    _eId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("eId");
                    OneIdChanged();
                }
            }
        }
        private global::System.Int32 _eId;
        partial void OneIdChanging(global::System.Int32 value);
        partial void OneIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eNumber
        {
            get
            {
                return _eNumber;
            }
            set
            {
                OneNumberChanging(value);
                ReportPropertyChanging("eNumber");
                _eNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eNumber");
                OneNumberChanged();
            }
        }
        private global::System.String _eNumber;
        partial void OneNumberChanging(global::System.String value);
        partial void OneNumberChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eName
        {
            get
            {
                return _eName;
            }
            set
            {
                OneNameChanging(value);
                ReportPropertyChanging("eName");
                _eName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eName");
                OneNameChanged();
            }
        }
        private global::System.String _eName;
        partial void OneNameChanging(global::System.String value);
        partial void OneNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ePhone
        {
            get
            {
                return _ePhone;
            }
            set
            {
                OnePhoneChanging(value);
                ReportPropertyChanging("ePhone");
                _ePhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ePhone");
                OnePhoneChanged();
            }
        }
        private global::System.String _ePhone;
        partial void OnePhoneChanging(global::System.String value);
        partial void OnePhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eRemark
        {
            get
            {
                return _eRemark;
            }
            set
            {
                OneRemarkChanging(value);
                ReportPropertyChanging("eRemark");
                _eRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eRemark");
                OneRemarkChanged();
            }
        }
        private global::System.String _eRemark;
        partial void OneRemarkChanging(global::System.String value);
        partial void OneRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MaryKayDBModel", Name="tbl_questions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_questions : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_questions 对象。
        /// </summary>
        /// <param name="qId">qId 属性的初始值。</param>
        public static tbl_questions Createtbl_questions(global::System.Int32 qId)
        {
            tbl_questions tbl_questions = new tbl_questions();
            tbl_questions.qId = qId;
            return tbl_questions;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 qId
        {
            get
            {
                return _qId;
            }
            set
            {
                if (_qId != value)
                {
                    OnqIdChanging(value);
                    ReportPropertyChanging("qId");
                    _qId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("qId");
                    OnqIdChanged();
                }
            }
        }
        private global::System.Int32 _qId;
        partial void OnqIdChanging(global::System.Int32 value);
        partial void OnqIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String qTitle
        {
            get
            {
                return _qTitle;
            }
            set
            {
                OnqTitleChanging(value);
                ReportPropertyChanging("qTitle");
                _qTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("qTitle");
                OnqTitleChanged();
            }
        }
        private global::System.String _qTitle;
        partial void OnqTitleChanging(global::System.String value);
        partial void OnqTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> qType
        {
            get
            {
                return _qType;
            }
            set
            {
                OnqTypeChanging(value);
                ReportPropertyChanging("qType");
                _qType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qType");
                OnqTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _qType;
        partial void OnqTypeChanging(Nullable<global::System.Int32> value);
        partial void OnqTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String qRemark
        {
            get
            {
                return _qRemark;
            }
            set
            {
                OnqRemarkChanging(value);
                ReportPropertyChanging("qRemark");
                _qRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("qRemark");
                OnqRemarkChanged();
            }
        }
        private global::System.String _qRemark;
        partial void OnqRemarkChanging(global::System.String value);
        partial void OnqRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MaryKayDBModel", Name="tbl_record")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_record : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_record 对象。
        /// </summary>
        /// <param name="rId">rId 属性的初始值。</param>
        public static tbl_record Createtbl_record(global::System.Int32 rId)
        {
            tbl_record tbl_record = new tbl_record();
            tbl_record.rId = rId;
            return tbl_record;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 rId
        {
            get
            {
                return _rId;
            }
            set
            {
                if (_rId != value)
                {
                    OnrIdChanging(value);
                    ReportPropertyChanging("rId");
                    _rId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("rId");
                    OnrIdChanged();
                }
            }
        }
        private global::System.Int32 _rId;
        partial void OnrIdChanging(global::System.Int32 value);
        partial void OnrIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> eId
        {
            get
            {
                return _eId;
            }
            set
            {
                OneIdChanging(value);
                ReportPropertyChanging("eId");
                _eId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eId");
                OneIdChanged();
            }
        }
        private Nullable<global::System.Int32> _eId;
        partial void OneIdChanging(Nullable<global::System.Int32> value);
        partial void OneIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> rBegintime
        {
            get
            {
                return _rBegintime;
            }
            set
            {
                OnrBegintimeChanging(value);
                ReportPropertyChanging("rBegintime");
                _rBegintime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rBegintime");
                OnrBegintimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _rBegintime;
        partial void OnrBegintimeChanging(Nullable<global::System.DateTime> value);
        partial void OnrBegintimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> rEndtime
        {
            get
            {
                return _rEndtime;
            }
            set
            {
                OnrEndtimeChanging(value);
                ReportPropertyChanging("rEndtime");
                _rEndtime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rEndtime");
                OnrEndtimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _rEndtime;
        partial void OnrEndtimeChanging(Nullable<global::System.DateTime> value);
        partial void OnrEndtimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> rDuration
        {
            get
            {
                return _rDuration;
            }
            set
            {
                OnrDurationChanging(value);
                ReportPropertyChanging("rDuration");
                _rDuration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rDuration");
                OnrDurationChanged();
            }
        }
        private Nullable<global::System.Int32> _rDuration;
        partial void OnrDurationChanging(Nullable<global::System.Int32> value);
        partial void OnrDurationChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rRemark
        {
            get
            {
                return _rRemark;
            }
            set
            {
                OnrRemarkChanging(value);
                ReportPropertyChanging("rRemark");
                _rRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rRemark");
                OnrRemarkChanged();
            }
        }
        private global::System.String _rRemark;
        partial void OnrRemarkChanging(global::System.String value);
        partial void OnrRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MaryKayDBModel", Name="tbl_view")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_view : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_view 对象。
        /// </summary>
        /// <param name="vId">vId 属性的初始值。</param>
        public static tbl_view Createtbl_view(global::System.Int32 vId)
        {
            tbl_view tbl_view = new tbl_view();
            tbl_view.vId = vId;
            return tbl_view;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 vId
        {
            get
            {
                return _vId;
            }
            set
            {
                if (_vId != value)
                {
                    OnvIdChanging(value);
                    ReportPropertyChanging("vId");
                    _vId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("vId");
                    OnvIdChanged();
                }
            }
        }
        private global::System.Int32 _vId;
        partial void OnvIdChanging(global::System.Int32 value);
        partial void OnvIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> viewCount
        {
            get
            {
                return _viewCount;
            }
            set
            {
                OnviewCountChanging(value);
                ReportPropertyChanging("viewCount");
                _viewCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("viewCount");
                OnviewCountChanged();
            }
        }
        private Nullable<global::System.Int32> _viewCount;
        partial void OnviewCountChanging(Nullable<global::System.Int32> value);
        partial void OnviewCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String viewRemark
        {
            get
            {
                return _viewRemark;
            }
            set
            {
                OnviewRemarkChanging(value);
                ReportPropertyChanging("viewRemark");
                _viewRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("viewRemark");
                OnviewRemarkChanged();
            }
        }
        private global::System.String _viewRemark;
        partial void OnviewRemarkChanging(global::System.String value);
        partial void OnviewRemarkChanged();

        #endregion

    
    }

    #endregion

    
}
