//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WebApp.DB
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class VoteAndQuestionDBEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“VoteAndQuestionDBEntities”部分中的连接字符串初始化新 VoteAndQuestionDBEntities 对象。
        /// </summary>
        public VoteAndQuestionDBEntities() : base("name=VoteAndQuestionDBEntities", "VoteAndQuestionDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 VoteAndQuestionDBEntities 对象。
        /// </summary>
        public VoteAndQuestionDBEntities(string connectionString) : base(connectionString, "VoteAndQuestionDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 VoteAndQuestionDBEntities 对象。
        /// </summary>
        public VoteAndQuestionDBEntities(EntityConnection connection) : base(connection, "VoteAndQuestionDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_WechatUser> tbl_WechatUser
        {
            get
            {
                if ((_tbl_WechatUser == null))
                {
                    _tbl_WechatUser = base.CreateObjectSet<tbl_WechatUser>("tbl_WechatUser");
                }
                return _tbl_WechatUser;
            }
        }
        private ObjectSet<tbl_WechatUser> _tbl_WechatUser;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_Theme> tbl_Theme
        {
            get
            {
                if ((_tbl_Theme == null))
                {
                    _tbl_Theme = base.CreateObjectSet<tbl_Theme>("tbl_Theme");
                }
                return _tbl_Theme;
            }
        }
        private ObjectSet<tbl_Theme> _tbl_Theme;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_Question> tbl_Question
        {
            get
            {
                if ((_tbl_Question == null))
                {
                    _tbl_Question = base.CreateObjectSet<tbl_Question>("tbl_Question");
                }
                return _tbl_Question;
            }
        }
        private ObjectSet<tbl_Question> _tbl_Question;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_VoteItem> tbl_VoteItem
        {
            get
            {
                if ((_tbl_VoteItem == null))
                {
                    _tbl_VoteItem = base.CreateObjectSet<tbl_VoteItem>("tbl_VoteItem");
                }
                return _tbl_VoteItem;
            }
        }
        private ObjectSet<tbl_VoteItem> _tbl_VoteItem;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_VoteRecord> tbl_VoteRecord
        {
            get
            {
                if ((_tbl_VoteRecord == null))
                {
                    _tbl_VoteRecord = base.CreateObjectSet<tbl_VoteRecord>("tbl_VoteRecord");
                }
                return _tbl_VoteRecord;
            }
        }
        private ObjectSet<tbl_VoteRecord> _tbl_VoteRecord;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_Vote> tbl_Vote
        {
            get
            {
                if ((_tbl_Vote == null))
                {
                    _tbl_Vote = base.CreateObjectSet<tbl_Vote>("tbl_Vote");
                }
                return _tbl_Vote;
            }
        }
        private ObjectSet<tbl_Vote> _tbl_Vote;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_Receipt> tbl_Receipt
        {
            get
            {
                if ((_tbl_Receipt == null))
                {
                    _tbl_Receipt = base.CreateObjectSet<tbl_Receipt>("tbl_Receipt");
                }
                return _tbl_Receipt;
            }
        }
        private ObjectSet<tbl_Receipt> _tbl_Receipt;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_Abbvie> tbl_Abbvie
        {
            get
            {
                if ((_tbl_Abbvie == null))
                {
                    _tbl_Abbvie = base.CreateObjectSet<tbl_Abbvie>("tbl_Abbvie");
                }
                return _tbl_Abbvie;
            }
        }
        private ObjectSet<tbl_Abbvie> _tbl_Abbvie;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_employeeMK> tbl_employeeMK
        {
            get
            {
                if ((_tbl_employeeMK == null))
                {
                    _tbl_employeeMK = base.CreateObjectSet<tbl_employeeMK>("tbl_employeeMK");
                }
                return _tbl_employeeMK;
            }
        }
        private ObjectSet<tbl_employeeMK> _tbl_employeeMK;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<xm_Employee> xm_Employee
        {
            get
            {
                if ((_xm_Employee == null))
                {
                    _xm_Employee = base.CreateObjectSet<xm_Employee>("xm_Employee");
                }
                return _xm_Employee;
            }
        }
        private ObjectSet<xm_Employee> _xm_Employee;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<xm_Msg> xm_Msg
        {
            get
            {
                if ((_xm_Msg == null))
                {
                    _xm_Msg = base.CreateObjectSet<xm_Msg>("xm_Msg");
                }
                return _xm_Msg;
            }
        }
        private ObjectSet<xm_Msg> _xm_Msg;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 tbl_WechatUser EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_WechatUser(tbl_WechatUser tbl_WechatUser)
        {
            base.AddObject("tbl_WechatUser", tbl_WechatUser);
        }
    
        /// <summary>
        /// 用于向 tbl_Theme EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_Theme(tbl_Theme tbl_Theme)
        {
            base.AddObject("tbl_Theme", tbl_Theme);
        }
    
        /// <summary>
        /// 用于向 tbl_Question EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_Question(tbl_Question tbl_Question)
        {
            base.AddObject("tbl_Question", tbl_Question);
        }
    
        /// <summary>
        /// 用于向 tbl_VoteItem EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_VoteItem(tbl_VoteItem tbl_VoteItem)
        {
            base.AddObject("tbl_VoteItem", tbl_VoteItem);
        }
    
        /// <summary>
        /// 用于向 tbl_VoteRecord EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_VoteRecord(tbl_VoteRecord tbl_VoteRecord)
        {
            base.AddObject("tbl_VoteRecord", tbl_VoteRecord);
        }
    
        /// <summary>
        /// 用于向 tbl_Vote EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_Vote(tbl_Vote tbl_Vote)
        {
            base.AddObject("tbl_Vote", tbl_Vote);
        }
    
        /// <summary>
        /// 用于向 tbl_Receipt EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_Receipt(tbl_Receipt tbl_Receipt)
        {
            base.AddObject("tbl_Receipt", tbl_Receipt);
        }
    
        /// <summary>
        /// 用于向 tbl_Abbvie EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_Abbvie(tbl_Abbvie tbl_Abbvie)
        {
            base.AddObject("tbl_Abbvie", tbl_Abbvie);
        }
    
        /// <summary>
        /// 用于向 tbl_employeeMK EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_employeeMK(tbl_employeeMK tbl_employeeMK)
        {
            base.AddObject("tbl_employeeMK", tbl_employeeMK);
        }
    
        /// <summary>
        /// 用于向 xm_Employee EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToxm_Employee(xm_Employee xm_Employee)
        {
            base.AddObject("xm_Employee", xm_Employee);
        }
    
        /// <summary>
        /// 用于向 xm_Msg EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToxm_Msg(xm_Msg xm_Msg)
        {
            base.AddObject("xm_Msg", xm_Msg);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VoteAndQuestionDBModel", Name="tbl_Abbvie")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Abbvie : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_Abbvie 对象。
        /// </summary>
        /// <param name="aId">aId 属性的初始值。</param>
        public static tbl_Abbvie Createtbl_Abbvie(global::System.Int32 aId)
        {
            tbl_Abbvie tbl_Abbvie = new tbl_Abbvie();
            tbl_Abbvie.aId = aId;
            return tbl_Abbvie;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 aId
        {
            get
            {
                return _aId;
            }
            set
            {
                if (_aId != value)
                {
                    OnaIdChanging(value);
                    ReportPropertyChanging("aId");
                    _aId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("aId");
                    OnaIdChanged();
                }
            }
        }
        private global::System.Int32 _aId;
        partial void OnaIdChanging(global::System.Int32 value);
        partial void OnaIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aName
        {
            get
            {
                return _aName;
            }
            set
            {
                OnaNameChanging(value);
                ReportPropertyChanging("aName");
                _aName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("aName");
                OnaNameChanged();
            }
        }
        private global::System.String _aName;
        partial void OnaNameChanging(global::System.String value);
        partial void OnaNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aDept
        {
            get
            {
                return _aDept;
            }
            set
            {
                OnaDeptChanging(value);
                ReportPropertyChanging("aDept");
                _aDept = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("aDept");
                OnaDeptChanged();
            }
        }
        private global::System.String _aDept;
        partial void OnaDeptChanging(global::System.String value);
        partial void OnaDeptChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aImgName
        {
            get
            {
                return _aImgName;
            }
            set
            {
                OnaImgNameChanging(value);
                ReportPropertyChanging("aImgName");
                _aImgName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("aImgName");
                OnaImgNameChanged();
            }
        }
        private global::System.String _aImgName;
        partial void OnaImgNameChanging(global::System.String value);
        partial void OnaImgNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String aMessage
        {
            get
            {
                return _aMessage;
            }
            set
            {
                OnaMessageChanging(value);
                ReportPropertyChanging("aMessage");
                _aMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("aMessage");
                OnaMessageChanged();
            }
        }
        private global::System.String _aMessage;
        partial void OnaMessageChanging(global::System.String value);
        partial void OnaMessageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> aCreateTime
        {
            get
            {
                return _aCreateTime;
            }
            set
            {
                OnaCreateTimeChanging(value);
                ReportPropertyChanging("aCreateTime");
                _aCreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("aCreateTime");
                OnaCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _aCreateTime;
        partial void OnaCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnaCreateTimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VoteAndQuestionDBModel", Name="tbl_employeeMK")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_employeeMK : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_employeeMK 对象。
        /// </summary>
        /// <param name="eId">eId 属性的初始值。</param>
        public static tbl_employeeMK Createtbl_employeeMK(global::System.Int32 eId)
        {
            tbl_employeeMK tbl_employeeMK = new tbl_employeeMK();
            tbl_employeeMK.eId = eId;
            return tbl_employeeMK;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 eId
        {
            get
            {
                return _eId;
            }
            set
            {
                if (_eId != value)
                {
                    OneIdChanging(value);
                    ReportPropertyChanging("eId");
                    _eId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("eId");
                    OneIdChanged();
                }
            }
        }
        private global::System.Int32 _eId;
        partial void OneIdChanging(global::System.Int32 value);
        partial void OneIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eNumber
        {
            get
            {
                return _eNumber;
            }
            set
            {
                OneNumberChanging(value);
                ReportPropertyChanging("eNumber");
                _eNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eNumber");
                OneNumberChanged();
            }
        }
        private global::System.String _eNumber;
        partial void OneNumberChanging(global::System.String value);
        partial void OneNumberChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eName
        {
            get
            {
                return _eName;
            }
            set
            {
                OneNameChanging(value);
                ReportPropertyChanging("eName");
                _eName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eName");
                OneNameChanged();
            }
        }
        private global::System.String _eName;
        partial void OneNameChanging(global::System.String value);
        partial void OneNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ePhone
        {
            get
            {
                return _ePhone;
            }
            set
            {
                OnePhoneChanging(value);
                ReportPropertyChanging("ePhone");
                _ePhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ePhone");
                OnePhoneChanged();
            }
        }
        private global::System.String _ePhone;
        partial void OnePhoneChanging(global::System.String value);
        partial void OnePhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eRemark
        {
            get
            {
                return _eRemark;
            }
            set
            {
                OneRemarkChanging(value);
                ReportPropertyChanging("eRemark");
                _eRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eRemark");
                OneRemarkChanged();
            }
        }
        private global::System.String _eRemark;
        partial void OneRemarkChanging(global::System.String value);
        partial void OneRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VoteAndQuestionDBModel", Name="tbl_Question")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Question : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_Question 对象。
        /// </summary>
        /// <param name="qId">qId 属性的初始值。</param>
        public static tbl_Question Createtbl_Question(global::System.Int32 qId)
        {
            tbl_Question tbl_Question = new tbl_Question();
            tbl_Question.qId = qId;
            return tbl_Question;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 qId
        {
            get
            {
                return _qId;
            }
            set
            {
                if (_qId != value)
                {
                    OnqIdChanging(value);
                    ReportPropertyChanging("qId");
                    _qId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("qId");
                    OnqIdChanged();
                }
            }
        }
        private global::System.Int32 _qId;
        partial void OnqIdChanging(global::System.Int32 value);
        partial void OnqIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> tId
        {
            get
            {
                return _tId;
            }
            set
            {
                OntIdChanging(value);
                ReportPropertyChanging("tId");
                _tId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("tId");
                OntIdChanged();
            }
        }
        private Nullable<global::System.Int32> _tId;
        partial void OntIdChanging(Nullable<global::System.Int32> value);
        partial void OntIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String openId
        {
            get
            {
                return _openId;
            }
            set
            {
                OnopenIdChanging(value);
                ReportPropertyChanging("openId");
                _openId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("openId");
                OnopenIdChanged();
            }
        }
        private global::System.String _openId;
        partial void OnopenIdChanging(global::System.String value);
        partial void OnopenIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> qState
        {
            get
            {
                return _qState;
            }
            set
            {
                OnqStateChanging(value);
                ReportPropertyChanging("qState");
                _qState = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qState");
                OnqStateChanged();
            }
        }
        private Nullable<global::System.Int32> _qState;
        partial void OnqStateChanging(Nullable<global::System.Int32> value);
        partial void OnqStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String qContent
        {
            get
            {
                return _qContent;
            }
            set
            {
                OnqContentChanging(value);
                ReportPropertyChanging("qContent");
                _qContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("qContent");
                OnqContentChanged();
            }
        }
        private global::System.String _qContent;
        partial void OnqContentChanging(global::System.String value);
        partial void OnqContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> qCreateTime
        {
            get
            {
                return _qCreateTime;
            }
            set
            {
                OnqCreateTimeChanging(value);
                ReportPropertyChanging("qCreateTime");
                _qCreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qCreateTime");
                OnqCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _qCreateTime;
        partial void OnqCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnqCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String qRemark
        {
            get
            {
                return _qRemark;
            }
            set
            {
                OnqRemarkChanging(value);
                ReportPropertyChanging("qRemark");
                _qRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("qRemark");
                OnqRemarkChanged();
            }
        }
        private global::System.String _qRemark;
        partial void OnqRemarkChanging(global::System.String value);
        partial void OnqRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VoteAndQuestionDBModel", Name="tbl_Receipt")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Receipt : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_Receipt 对象。
        /// </summary>
        /// <param name="rId">rId 属性的初始值。</param>
        public static tbl_Receipt Createtbl_Receipt(global::System.Int32 rId)
        {
            tbl_Receipt tbl_Receipt = new tbl_Receipt();
            tbl_Receipt.rId = rId;
            return tbl_Receipt;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 rId
        {
            get
            {
                return _rId;
            }
            set
            {
                if (_rId != value)
                {
                    OnrIdChanging(value);
                    ReportPropertyChanging("rId");
                    _rId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("rId");
                    OnrIdChanged();
                }
            }
        }
        private global::System.Int32 _rId;
        partial void OnrIdChanging(global::System.Int32 value);
        partial void OnrIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rName
        {
            get
            {
                return _rName;
            }
            set
            {
                OnrNameChanging(value);
                ReportPropertyChanging("rName");
                _rName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rName");
                OnrNameChanged();
            }
        }
        private global::System.String _rName;
        partial void OnrNameChanging(global::System.String value);
        partial void OnrNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rDept
        {
            get
            {
                return _rDept;
            }
            set
            {
                OnrDeptChanging(value);
                ReportPropertyChanging("rDept");
                _rDept = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rDept");
                OnrDeptChanged();
            }
        }
        private global::System.String _rDept;
        partial void OnrDeptChanging(global::System.String value);
        partial void OnrDeptChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rPhone
        {
            get
            {
                return _rPhone;
            }
            set
            {
                OnrPhoneChanging(value);
                ReportPropertyChanging("rPhone");
                _rPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rPhone");
                OnrPhoneChanged();
            }
        }
        private global::System.String _rPhone;
        partial void OnrPhoneChanging(global::System.String value);
        partial void OnrPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rCode
        {
            get
            {
                return _rCode;
            }
            set
            {
                OnrCodeChanging(value);
                ReportPropertyChanging("rCode");
                _rCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rCode");
                OnrCodeChanged();
            }
        }
        private global::System.String _rCode;
        partial void OnrCodeChanging(global::System.String value);
        partial void OnrCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rBeginTime
        {
            get
            {
                return _rBeginTime;
            }
            set
            {
                OnrBeginTimeChanging(value);
                ReportPropertyChanging("rBeginTime");
                _rBeginTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rBeginTime");
                OnrBeginTimeChanged();
            }
        }
        private global::System.String _rBeginTime;
        partial void OnrBeginTimeChanging(global::System.String value);
        partial void OnrBeginTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rEndTime
        {
            get
            {
                return _rEndTime;
            }
            set
            {
                OnrEndTimeChanging(value);
                ReportPropertyChanging("rEndTime");
                _rEndTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rEndTime");
                OnrEndTimeChanged();
            }
        }
        private global::System.String _rEndTime;
        partial void OnrEndTimeChanging(global::System.String value);
        partial void OnrEndTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rBeginAddress
        {
            get
            {
                return _rBeginAddress;
            }
            set
            {
                OnrBeginAddressChanging(value);
                ReportPropertyChanging("rBeginAddress");
                _rBeginAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rBeginAddress");
                OnrBeginAddressChanged();
            }
        }
        private global::System.String _rBeginAddress;
        partial void OnrBeginAddressChanging(global::System.String value);
        partial void OnrBeginAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rEndAddress
        {
            get
            {
                return _rEndAddress;
            }
            set
            {
                OnrEndAddressChanging(value);
                ReportPropertyChanging("rEndAddress");
                _rEndAddress = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rEndAddress");
                OnrEndAddressChanged();
            }
        }
        private global::System.String _rEndAddress;
        partial void OnrEndAddressChanging(global::System.String value);
        partial void OnrEndAddressChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rStay
        {
            get
            {
                return _rStay;
            }
            set
            {
                OnrStayChanging(value);
                ReportPropertyChanging("rStay");
                _rStay = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rStay");
                OnrStayChanged();
            }
        }
        private global::System.String _rStay;
        partial void OnrStayChanging(global::System.String value);
        partial void OnrStayChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rTravel
        {
            get
            {
                return _rTravel;
            }
            set
            {
                OnrTravelChanging(value);
                ReportPropertyChanging("rTravel");
                _rTravel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rTravel");
                OnrTravelChanged();
            }
        }
        private global::System.String _rTravel;
        partial void OnrTravelChanging(global::System.String value);
        partial void OnrTravelChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rPeople
        {
            get
            {
                return _rPeople;
            }
            set
            {
                OnrPeopleChanging(value);
                ReportPropertyChanging("rPeople");
                _rPeople = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rPeople");
                OnrPeopleChanged();
            }
        }
        private global::System.String _rPeople;
        partial void OnrPeopleChanging(global::System.String value);
        partial void OnrPeopleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String rPeopleTell
        {
            get
            {
                return _rPeopleTell;
            }
            set
            {
                OnrPeopleTellChanging(value);
                ReportPropertyChanging("rPeopleTell");
                _rPeopleTell = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("rPeopleTell");
                OnrPeopleTellChanged();
            }
        }
        private global::System.String _rPeopleTell;
        partial void OnrPeopleTellChanging(global::System.String value);
        partial void OnrPeopleTellChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> rCreateTime
        {
            get
            {
                return _rCreateTime;
            }
            set
            {
                OnrCreateTimeChanging(value);
                ReportPropertyChanging("rCreateTime");
                _rCreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("rCreateTime");
                OnrCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _rCreateTime;
        partial void OnrCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnrCreateTimeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VoteAndQuestionDBModel", Name="tbl_Theme")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Theme : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_Theme 对象。
        /// </summary>
        /// <param name="themeId">themeId 属性的初始值。</param>
        public static tbl_Theme Createtbl_Theme(global::System.Int32 themeId)
        {
            tbl_Theme tbl_Theme = new tbl_Theme();
            tbl_Theme.themeId = themeId;
            return tbl_Theme;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 themeId
        {
            get
            {
                return _themeId;
            }
            set
            {
                if (_themeId != value)
                {
                    OnthemeIdChanging(value);
                    ReportPropertyChanging("themeId");
                    _themeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("themeId");
                    OnthemeIdChanged();
                }
            }
        }
        private global::System.Int32 _themeId;
        partial void OnthemeIdChanging(global::System.Int32 value);
        partial void OnthemeIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String themeTitle
        {
            get
            {
                return _themeTitle;
            }
            set
            {
                OnthemeTitleChanging(value);
                ReportPropertyChanging("themeTitle");
                _themeTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("themeTitle");
                OnthemeTitleChanged();
            }
        }
        private global::System.String _themeTitle;
        partial void OnthemeTitleChanging(global::System.String value);
        partial void OnthemeTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> themeState
        {
            get
            {
                return _themeState;
            }
            set
            {
                OnthemeStateChanging(value);
                ReportPropertyChanging("themeState");
                _themeState = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("themeState");
                OnthemeStateChanged();
            }
        }
        private Nullable<global::System.Int32> _themeState;
        partial void OnthemeStateChanging(Nullable<global::System.Int32> value);
        partial void OnthemeStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String themeBeginTime
        {
            get
            {
                return _themeBeginTime;
            }
            set
            {
                OnthemeBeginTimeChanging(value);
                ReportPropertyChanging("themeBeginTime");
                _themeBeginTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("themeBeginTime");
                OnthemeBeginTimeChanged();
            }
        }
        private global::System.String _themeBeginTime;
        partial void OnthemeBeginTimeChanging(global::System.String value);
        partial void OnthemeBeginTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String themeEndTime
        {
            get
            {
                return _themeEndTime;
            }
            set
            {
                OnthemeEndTimeChanging(value);
                ReportPropertyChanging("themeEndTime");
                _themeEndTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("themeEndTime");
                OnthemeEndTimeChanged();
            }
        }
        private global::System.String _themeEndTime;
        partial void OnthemeEndTimeChanging(global::System.String value);
        partial void OnthemeEndTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> themeCreateTime
        {
            get
            {
                return _themeCreateTime;
            }
            set
            {
                OnthemeCreateTimeChanging(value);
                ReportPropertyChanging("themeCreateTime");
                _themeCreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("themeCreateTime");
                OnthemeCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _themeCreateTime;
        partial void OnthemeCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnthemeCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String themeRemarks
        {
            get
            {
                return _themeRemarks;
            }
            set
            {
                OnthemeRemarksChanging(value);
                ReportPropertyChanging("themeRemarks");
                _themeRemarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("themeRemarks");
                OnthemeRemarksChanged();
            }
        }
        private global::System.String _themeRemarks;
        partial void OnthemeRemarksChanging(global::System.String value);
        partial void OnthemeRemarksChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VoteAndQuestionDBModel", Name="tbl_Vote")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Vote : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_Vote 对象。
        /// </summary>
        /// <param name="vId">vId 属性的初始值。</param>
        public static tbl_Vote Createtbl_Vote(global::System.Int32 vId)
        {
            tbl_Vote tbl_Vote = new tbl_Vote();
            tbl_Vote.vId = vId;
            return tbl_Vote;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 vId
        {
            get
            {
                return _vId;
            }
            set
            {
                if (_vId != value)
                {
                    OnvIdChanging(value);
                    ReportPropertyChanging("vId");
                    _vId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("vId");
                    OnvIdChanged();
                }
            }
        }
        private global::System.Int32 _vId;
        partial void OnvIdChanging(global::System.Int32 value);
        partial void OnvIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vTitle
        {
            get
            {
                return _vTitle;
            }
            set
            {
                OnvTitleChanging(value);
                ReportPropertyChanging("vTitle");
                _vTitle = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vTitle");
                OnvTitleChanged();
            }
        }
        private global::System.String _vTitle;
        partial void OnvTitleChanging(global::System.String value);
        partial void OnvTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> vType
        {
            get
            {
                return _vType;
            }
            set
            {
                OnvTypeChanging(value);
                ReportPropertyChanging("vType");
                _vType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vType");
                OnvTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _vType;
        partial void OnvTypeChanging(Nullable<global::System.Int32> value);
        partial void OnvTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> vState
        {
            get
            {
                return _vState;
            }
            set
            {
                OnvStateChanging(value);
                ReportPropertyChanging("vState");
                _vState = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vState");
                OnvStateChanged();
            }
        }
        private Nullable<global::System.Int32> _vState;
        partial void OnvStateChanging(Nullable<global::System.Int32> value);
        partial void OnvStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vBeginTime
        {
            get
            {
                return _vBeginTime;
            }
            set
            {
                OnvBeginTimeChanging(value);
                ReportPropertyChanging("vBeginTime");
                _vBeginTime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vBeginTime");
                OnvBeginTimeChanged();
            }
        }
        private global::System.String _vBeginTime;
        partial void OnvBeginTimeChanging(global::System.String value);
        partial void OnvBeginTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> vCreateTime
        {
            get
            {
                return _vCreateTime;
            }
            set
            {
                OnvCreateTimeChanging(value);
                ReportPropertyChanging("vCreateTime");
                _vCreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vCreateTime");
                OnvCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _vCreateTime;
        partial void OnvCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnvCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vRemark
        {
            get
            {
                return _vRemark;
            }
            set
            {
                OnvRemarkChanging(value);
                ReportPropertyChanging("vRemark");
                _vRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vRemark");
                OnvRemarkChanged();
            }
        }
        private global::System.String _vRemark;
        partial void OnvRemarkChanging(global::System.String value);
        partial void OnvRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VoteAndQuestionDBModel", Name="tbl_VoteItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_VoteItem : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_VoteItem 对象。
        /// </summary>
        /// <param name="itemId">itemId 属性的初始值。</param>
        public static tbl_VoteItem Createtbl_VoteItem(global::System.Int32 itemId)
        {
            tbl_VoteItem tbl_VoteItem = new tbl_VoteItem();
            tbl_VoteItem.itemId = itemId;
            return tbl_VoteItem;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 itemId
        {
            get
            {
                return _itemId;
            }
            set
            {
                if (_itemId != value)
                {
                    OnitemIdChanging(value);
                    ReportPropertyChanging("itemId");
                    _itemId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("itemId");
                    OnitemIdChanged();
                }
            }
        }
        private global::System.Int32 _itemId;
        partial void OnitemIdChanging(global::System.Int32 value);
        partial void OnitemIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> itemVId
        {
            get
            {
                return _itemVId;
            }
            set
            {
                OnitemVIdChanging(value);
                ReportPropertyChanging("itemVId");
                _itemVId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("itemVId");
                OnitemVIdChanged();
            }
        }
        private Nullable<global::System.Int32> _itemVId;
        partial void OnitemVIdChanging(Nullable<global::System.Int32> value);
        partial void OnitemVIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String itemValue
        {
            get
            {
                return _itemValue;
            }
            set
            {
                OnitemValueChanging(value);
                ReportPropertyChanging("itemValue");
                _itemValue = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("itemValue");
                OnitemValueChanged();
            }
        }
        private global::System.String _itemValue;
        partial void OnitemValueChanging(global::System.String value);
        partial void OnitemValueChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String itemContent
        {
            get
            {
                return _itemContent;
            }
            set
            {
                OnitemContentChanging(value);
                ReportPropertyChanging("itemContent");
                _itemContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("itemContent");
                OnitemContentChanged();
            }
        }
        private global::System.String _itemContent;
        partial void OnitemContentChanging(global::System.String value);
        partial void OnitemContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String itemRemark
        {
            get
            {
                return _itemRemark;
            }
            set
            {
                OnitemRemarkChanging(value);
                ReportPropertyChanging("itemRemark");
                _itemRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("itemRemark");
                OnitemRemarkChanged();
            }
        }
        private global::System.String _itemRemark;
        partial void OnitemRemarkChanging(global::System.String value);
        partial void OnitemRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VoteAndQuestionDBModel", Name="tbl_VoteRecord")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_VoteRecord : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_VoteRecord 对象。
        /// </summary>
        /// <param name="vrId">vrId 属性的初始值。</param>
        public static tbl_VoteRecord Createtbl_VoteRecord(global::System.Int32 vrId)
        {
            tbl_VoteRecord tbl_VoteRecord = new tbl_VoteRecord();
            tbl_VoteRecord.vrId = vrId;
            return tbl_VoteRecord;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 vrId
        {
            get
            {
                return _vrId;
            }
            set
            {
                if (_vrId != value)
                {
                    OnvrIdChanging(value);
                    ReportPropertyChanging("vrId");
                    _vrId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("vrId");
                    OnvrIdChanged();
                }
            }
        }
        private global::System.Int32 _vrId;
        partial void OnvrIdChanging(global::System.Int32 value);
        partial void OnvrIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> vId
        {
            get
            {
                return _vId;
            }
            set
            {
                OnvIdChanging(value);
                ReportPropertyChanging("vId");
                _vId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vId");
                OnvIdChanged();
            }
        }
        private Nullable<global::System.Int32> _vId;
        partial void OnvIdChanging(Nullable<global::System.Int32> value);
        partial void OnvIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wcOpenId
        {
            get
            {
                return _wcOpenId;
            }
            set
            {
                OnwcOpenIdChanging(value);
                ReportPropertyChanging("wcOpenId");
                _wcOpenId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("wcOpenId");
                OnwcOpenIdChanged();
            }
        }
        private global::System.String _wcOpenId;
        partial void OnwcOpenIdChanging(global::System.String value);
        partial void OnwcOpenIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> vItemId
        {
            get
            {
                return _vItemId;
            }
            set
            {
                OnvItemIdChanging(value);
                ReportPropertyChanging("vItemId");
                _vItemId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vItemId");
                OnvItemIdChanged();
            }
        }
        private Nullable<global::System.Int32> _vItemId;
        partial void OnvItemIdChanging(Nullable<global::System.Int32> value);
        partial void OnvItemIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vrContent
        {
            get
            {
                return _vrContent;
            }
            set
            {
                OnvrContentChanging(value);
                ReportPropertyChanging("vrContent");
                _vrContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vrContent");
                OnvrContentChanged();
            }
        }
        private global::System.String _vrContent;
        partial void OnvrContentChanging(global::System.String value);
        partial void OnvrContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> vrCreateTime
        {
            get
            {
                return _vrCreateTime;
            }
            set
            {
                OnvrCreateTimeChanging(value);
                ReportPropertyChanging("vrCreateTime");
                _vrCreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vrCreateTime");
                OnvrCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _vrCreateTime;
        partial void OnvrCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnvrCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vrRemark
        {
            get
            {
                return _vrRemark;
            }
            set
            {
                OnvrRemarkChanging(value);
                ReportPropertyChanging("vrRemark");
                _vrRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vrRemark");
                OnvrRemarkChanged();
            }
        }
        private global::System.String _vrRemark;
        partial void OnvrRemarkChanging(global::System.String value);
        partial void OnvrRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VoteAndQuestionDBModel", Name="tbl_WechatUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_WechatUser : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_WechatUser 对象。
        /// </summary>
        /// <param name="wcId">wcId 属性的初始值。</param>
        public static tbl_WechatUser Createtbl_WechatUser(global::System.Int32 wcId)
        {
            tbl_WechatUser tbl_WechatUser = new tbl_WechatUser();
            tbl_WechatUser.wcId = wcId;
            return tbl_WechatUser;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 wcId
        {
            get
            {
                return _wcId;
            }
            set
            {
                if (_wcId != value)
                {
                    OnwcIdChanging(value);
                    ReportPropertyChanging("wcId");
                    _wcId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("wcId");
                    OnwcIdChanged();
                }
            }
        }
        private global::System.Int32 _wcId;
        partial void OnwcIdChanging(global::System.Int32 value);
        partial void OnwcIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wcOpenId
        {
            get
            {
                return _wcOpenId;
            }
            set
            {
                OnwcOpenIdChanging(value);
                ReportPropertyChanging("wcOpenId");
                _wcOpenId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("wcOpenId");
                OnwcOpenIdChanged();
            }
        }
        private global::System.String _wcOpenId;
        partial void OnwcOpenIdChanging(global::System.String value);
        partial void OnwcOpenIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wcNickname
        {
            get
            {
                return _wcNickname;
            }
            set
            {
                OnwcNicknameChanging(value);
                ReportPropertyChanging("wcNickname");
                _wcNickname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("wcNickname");
                OnwcNicknameChanged();
            }
        }
        private global::System.String _wcNickname;
        partial void OnwcNicknameChanging(global::System.String value);
        partial void OnwcNicknameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wcSex
        {
            get
            {
                return _wcSex;
            }
            set
            {
                OnwcSexChanging(value);
                ReportPropertyChanging("wcSex");
                _wcSex = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("wcSex");
                OnwcSexChanged();
            }
        }
        private global::System.String _wcSex;
        partial void OnwcSexChanging(global::System.String value);
        partial void OnwcSexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wcHeadimgurl
        {
            get
            {
                return _wcHeadimgurl;
            }
            set
            {
                OnwcHeadimgurlChanging(value);
                ReportPropertyChanging("wcHeadimgurl");
                _wcHeadimgurl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("wcHeadimgurl");
                OnwcHeadimgurlChanged();
            }
        }
        private global::System.String _wcHeadimgurl;
        partial void OnwcHeadimgurlChanging(global::System.String value);
        partial void OnwcHeadimgurlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> wcCreateTime
        {
            get
            {
                return _wcCreateTime;
            }
            set
            {
                OnwcCreateTimeChanging(value);
                ReportPropertyChanging("wcCreateTime");
                _wcCreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("wcCreateTime");
                OnwcCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _wcCreateTime;
        partial void OnwcCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnwcCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String wcRemark
        {
            get
            {
                return _wcRemark;
            }
            set
            {
                OnwcRemarkChanging(value);
                ReportPropertyChanging("wcRemark");
                _wcRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("wcRemark");
                OnwcRemarkChanged();
            }
        }
        private global::System.String _wcRemark;
        partial void OnwcRemarkChanging(global::System.String value);
        partial void OnwcRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VoteAndQuestionDBModel", Name="xm_Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class xm_Employee : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 xm_Employee 对象。
        /// </summary>
        /// <param name="eId">eId 属性的初始值。</param>
        public static xm_Employee Createxm_Employee(global::System.Int32 eId)
        {
            xm_Employee xm_Employee = new xm_Employee();
            xm_Employee.eId = eId;
            return xm_Employee;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 eId
        {
            get
            {
                return _eId;
            }
            set
            {
                if (_eId != value)
                {
                    OneIdChanging(value);
                    ReportPropertyChanging("eId");
                    _eId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("eId");
                    OneIdChanged();
                }
            }
        }
        private global::System.Int32 _eId;
        partial void OneIdChanging(global::System.Int32 value);
        partial void OneIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eName
        {
            get
            {
                return _eName;
            }
            set
            {
                OneNameChanging(value);
                ReportPropertyChanging("eName");
                _eName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eName");
                OneNameChanged();
            }
        }
        private global::System.String _eName;
        partial void OneNameChanging(global::System.String value);
        partial void OneNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eEmail
        {
            get
            {
                return _eEmail;
            }
            set
            {
                OneEmailChanging(value);
                ReportPropertyChanging("eEmail");
                _eEmail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eEmail");
                OneEmailChanged();
            }
        }
        private global::System.String _eEmail;
        partial void OneEmailChanging(global::System.String value);
        partial void OneEmailChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> eSign
        {
            get
            {
                return _eSign;
            }
            set
            {
                OneSignChanging(value);
                ReportPropertyChanging("eSign");
                _eSign = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eSign");
                OneSignChanged();
            }
        }
        private Nullable<global::System.Boolean> _eSign;
        partial void OneSignChanging(Nullable<global::System.Boolean> value);
        partial void OneSignChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> eSignTime
        {
            get
            {
                return _eSignTime;
            }
            set
            {
                OneSignTimeChanging(value);
                ReportPropertyChanging("eSignTime");
                _eSignTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("eSignTime");
                OneSignTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _eSignTime;
        partial void OneSignTimeChanging(Nullable<global::System.DateTime> value);
        partial void OneSignTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String eRemark
        {
            get
            {
                return _eRemark;
            }
            set
            {
                OneRemarkChanging(value);
                ReportPropertyChanging("eRemark");
                _eRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("eRemark");
                OneRemarkChanged();
            }
        }
        private global::System.String _eRemark;
        partial void OneRemarkChanging(global::System.String value);
        partial void OneRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VoteAndQuestionDBModel", Name="xm_Msg")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class xm_Msg : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 xm_Msg 对象。
        /// </summary>
        /// <param name="mId">mId 属性的初始值。</param>
        public static xm_Msg Createxm_Msg(global::System.Int32 mId)
        {
            xm_Msg xm_Msg = new xm_Msg();
            xm_Msg.mId = mId;
            return xm_Msg;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 mId
        {
            get
            {
                return _mId;
            }
            set
            {
                if (_mId != value)
                {
                    OnmIdChanging(value);
                    ReportPropertyChanging("mId");
                    _mId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("mId");
                    OnmIdChanged();
                }
            }
        }
        private global::System.Int32 _mId;
        partial void OnmIdChanging(global::System.Int32 value);
        partial void OnmIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mContent
        {
            get
            {
                return _mContent;
            }
            set
            {
                OnmContentChanging(value);
                ReportPropertyChanging("mContent");
                _mContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mContent");
                OnmContentChanged();
            }
        }
        private global::System.String _mContent;
        partial void OnmContentChanging(global::System.String value);
        partial void OnmContentChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mCode
        {
            get
            {
                return _mCode;
            }
            set
            {
                OnmCodeChanging(value);
                ReportPropertyChanging("mCode");
                _mCode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mCode");
                OnmCodeChanged();
            }
        }
        private global::System.String _mCode;
        partial void OnmCodeChanging(global::System.String value);
        partial void OnmCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> mTime
        {
            get
            {
                return _mTime;
            }
            set
            {
                OnmTimeChanging(value);
                ReportPropertyChanging("mTime");
                _mTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mTime");
                OnmTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _mTime;
        partial void OnmTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnmTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> mState
        {
            get
            {
                return _mState;
            }
            set
            {
                OnmStateChanging(value);
                ReportPropertyChanging("mState");
                _mState = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mState");
                OnmStateChanged();
            }
        }
        private Nullable<global::System.Int32> _mState;
        partial void OnmStateChanging(Nullable<global::System.Int32> value);
        partial void OnmStateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> mIndex
        {
            get
            {
                return _mIndex;
            }
            set
            {
                OnmIndexChanging(value);
                ReportPropertyChanging("mIndex");
                _mIndex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("mIndex");
                OnmIndexChanged();
            }
        }
        private Nullable<global::System.Int32> _mIndex;
        partial void OnmIndexChanging(Nullable<global::System.Int32> value);
        partial void OnmIndexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String mRemark
        {
            get
            {
                return _mRemark;
            }
            set
            {
                OnmRemarkChanging(value);
                ReportPropertyChanging("mRemark");
                _mRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("mRemark");
                OnmRemarkChanged();
            }
        }
        private global::System.String _mRemark;
        partial void OnmRemarkChanging(global::System.String value);
        partial void OnmRemarkChanged();

        #endregion

    
    }

    #endregion

    
}
