//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WebApp.DB
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class WebService_DBEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“WebService_DBEntities”部分中的连接字符串初始化新 WebService_DBEntities 对象。
        /// </summary>
        public WebService_DBEntities() : base("name=WebService_DBEntities", "WebService_DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 WebService_DBEntities 对象。
        /// </summary>
        public WebService_DBEntities(string connectionString) : base(connectionString, "WebService_DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 WebService_DBEntities 对象。
        /// </summary>
        public WebService_DBEntities(EntityConnection connection) : base(connection, "WebService_DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_UploadImg> tbl_UploadImg
        {
            get
            {
                if ((_tbl_UploadImg == null))
                {
                    _tbl_UploadImg = base.CreateObjectSet<tbl_UploadImg>("tbl_UploadImg");
                }
                return _tbl_UploadImg;
            }
        }
        private ObjectSet<tbl_UploadImg> _tbl_UploadImg;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<tbl_VisitorInfo> tbl_VisitorInfo
        {
            get
            {
                if ((_tbl_VisitorInfo == null))
                {
                    _tbl_VisitorInfo = base.CreateObjectSet<tbl_VisitorInfo>("tbl_VisitorInfo");
                }
                return _tbl_VisitorInfo;
            }
        }
        private ObjectSet<tbl_VisitorInfo> _tbl_VisitorInfo;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 tbl_UploadImg EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_UploadImg(tbl_UploadImg tbl_UploadImg)
        {
            base.AddObject("tbl_UploadImg", tbl_UploadImg);
        }
    
        /// <summary>
        /// 用于向 tbl_VisitorInfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTotbl_VisitorInfo(tbl_VisitorInfo tbl_VisitorInfo)
        {
            base.AddObject("tbl_VisitorInfo", tbl_VisitorInfo);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WebService_DBModel", Name="tbl_UploadImg")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_UploadImg : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_UploadImg 对象。
        /// </summary>
        /// <param name="imgId">imgId 属性的初始值。</param>
        public static tbl_UploadImg Createtbl_UploadImg(global::System.Int32 imgId)
        {
            tbl_UploadImg tbl_UploadImg = new tbl_UploadImg();
            tbl_UploadImg.imgId = imgId;
            return tbl_UploadImg;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 imgId
        {
            get
            {
                return _imgId;
            }
            set
            {
                if (_imgId != value)
                {
                    OnimgIdChanging(value);
                    ReportPropertyChanging("imgId");
                    _imgId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("imgId");
                    OnimgIdChanged();
                }
            }
        }
        private global::System.Int32 _imgId;
        partial void OnimgIdChanging(global::System.Int32 value);
        partial void OnimgIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imgName
        {
            get
            {
                return _imgName;
            }
            set
            {
                OnimgNameChanging(value);
                ReportPropertyChanging("imgName");
                _imgName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imgName");
                OnimgNameChanged();
            }
        }
        private global::System.String _imgName;
        partial void OnimgNameChanging(global::System.String value);
        partial void OnimgNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imgProName
        {
            get
            {
                return _imgProName;
            }
            set
            {
                OnimgProNameChanging(value);
                ReportPropertyChanging("imgProName");
                _imgProName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imgProName");
                OnimgProNameChanged();
            }
        }
        private global::System.String _imgProName;
        partial void OnimgProNameChanging(global::System.String value);
        partial void OnimgProNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imgUrl
        {
            get
            {
                return _imgUrl;
            }
            set
            {
                OnimgUrlChanging(value);
                ReportPropertyChanging("imgUrl");
                _imgUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imgUrl");
                OnimgUrlChanged();
            }
        }
        private global::System.String _imgUrl;
        partial void OnimgUrlChanging(global::System.String value);
        partial void OnimgUrlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> imgIndex
        {
            get
            {
                return _imgIndex;
            }
            set
            {
                OnimgIndexChanging(value);
                ReportPropertyChanging("imgIndex");
                _imgIndex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("imgIndex");
                OnimgIndexChanged();
            }
        }
        private Nullable<global::System.Int32> _imgIndex;
        partial void OnimgIndexChanging(Nullable<global::System.Int32> value);
        partial void OnimgIndexChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> imgCreateTime
        {
            get
            {
                return _imgCreateTime;
            }
            set
            {
                OnimgCreateTimeChanging(value);
                ReportPropertyChanging("imgCreateTime");
                _imgCreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("imgCreateTime");
                OnimgCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _imgCreateTime;
        partial void OnimgCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnimgCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imgRemark
        {
            get
            {
                return _imgRemark;
            }
            set
            {
                OnimgRemarkChanging(value);
                ReportPropertyChanging("imgRemark");
                _imgRemark = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imgRemark");
                OnimgRemarkChanged();
            }
        }
        private global::System.String _imgRemark;
        partial void OnimgRemarkChanging(global::System.String value);
        partial void OnimgRemarkChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WebService_DBModel", Name="tbl_VisitorInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_VisitorInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 tbl_VisitorInfo 对象。
        /// </summary>
        /// <param name="vId">vId 属性的初始值。</param>
        public static tbl_VisitorInfo Createtbl_VisitorInfo(global::System.Int32 vId)
        {
            tbl_VisitorInfo tbl_VisitorInfo = new tbl_VisitorInfo();
            tbl_VisitorInfo.vId = vId;
            return tbl_VisitorInfo;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 vId
        {
            get
            {
                return _vId;
            }
            set
            {
                if (_vId != value)
                {
                    OnvIdChanging(value);
                    ReportPropertyChanging("vId");
                    _vId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("vId");
                    OnvIdChanged();
                }
            }
        }
        private global::System.Int32 _vId;
        partial void OnvIdChanging(global::System.Int32 value);
        partial void OnvIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vName
        {
            get
            {
                return _vName;
            }
            set
            {
                OnvNameChanging(value);
                ReportPropertyChanging("vName");
                _vName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vName");
                OnvNameChanged();
            }
        }
        private global::System.String _vName;
        partial void OnvNameChanging(global::System.String value);
        partial void OnvNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vPhone
        {
            get
            {
                return _vPhone;
            }
            set
            {
                OnvPhoneChanging(value);
                ReportPropertyChanging("vPhone");
                _vPhone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vPhone");
                OnvPhoneChanged();
            }
        }
        private global::System.String _vPhone;
        partial void OnvPhoneChanging(global::System.String value);
        partial void OnvPhoneChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String imgName
        {
            get
            {
                return _imgName;
            }
            set
            {
                OnimgNameChanging(value);
                ReportPropertyChanging("imgName");
                _imgName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("imgName");
                OnimgNameChanged();
            }
        }
        private global::System.String _imgName;
        partial void OnimgNameChanging(global::System.String value);
        partial void OnimgNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createTime
        {
            get
            {
                return _createTime;
            }
            set
            {
                OncreateTimeChanging(value);
                ReportPropertyChanging("createTime");
                _createTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createTime");
                OncreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _createTime;
        partial void OncreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OncreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String vRemarks
        {
            get
            {
                return _vRemarks;
            }
            set
            {
                OnvRemarksChanging(value);
                ReportPropertyChanging("vRemarks");
                _vRemarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("vRemarks");
                OnvRemarksChanged();
            }
        }
        private global::System.String _vRemarks;
        partial void OnvRemarksChanging(global::System.String value);
        partial void OnvRemarksChanged();

        #endregion

    
    }

    #endregion

    
}
